version: '3.8'

services:
  # Tempo - 分布式追踪后端
  tempo:
    image: grafana/tempo:2.3.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "9095:9095"   # tempo grpc
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - tempo

  svca:
    build:
      context: .
      dockerfile: ./svca/Dockerfile
      no_cache: true
    container_name: svca
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=svca
    depends_on:
      - tempo
      - grafana

  svcb:
    build:
      context: .
      dockerfile: ./svcb/Dockerfile
      no_cache: true
    container_name: svcb
    ports:
      - "50051:50051"
    environment:
      - SERVICE_NAME=svcb
    depends_on:
      - tempo
      - grafana


volumes:
  tempo-data:
  grafana-data: 