server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # 收集应用日志
  - job_name: application-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: application-logs
          __path__: /var/log/app/*.log 