version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: micro-svc-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: micro-svc-victoriametrics
    ports:
      - "8428:8428"
    volumes:
      - ./vm_data:/victoria-metrics-data
    command:
      - "-retentionPeriod=1y"
      - "-storageDataPath=/victoria-metrics-data"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: micro-svc-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin 