{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "P90|95|99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(myapp_http_request_duration_seconds_bucket{job=\"my-go-app\"}[5m])) by (le,path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(myapp_http_request_duration_seconds_bucket{job=\"my-go-app\"}[5m])) by (le, path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(myapp_http_request_duration_seconds_bucket[5m])) by (le,path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(myapp_http_requests_total{status_code=\"500\"}[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(myapp_http_request_duration_seconds_count[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}